import Head from "next/head";
import "./home.css";

import ChatWrapper from "../components/chat-components/ChatWrapper.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Langchain App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <ChatWrapper />
        </main>
      </div>
    </>
  );
}
